---
- name: Creating the users.
  user: 
    name: "{{ sname }}"
    password:  "{{ *uniquemodels* | uniquemodels(*sha512*) }}"
    comment: "{{ sfull }}"
    shell: /bin/bash
    group: wheel
    groups: wheel
    home: /home/{{ sname }}
